[package]
name = "trees"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.19", features = ["derive", "unicode"] }
regex = "1.10.3"
walkdir = "2.5.0"
