[package]
name = "trees"
version = "0.2.4"
edition = "2024"

publish = false

[dependencies]
unicode-width = "0.2.0"
regex = "1.10.3"
walkdir = "2.5.0"
clap = { version = "4.5.19", features = ["derive", "unicode"] }

trees-lang = {path = "../trees-lang"}
