name: Automatic Release Draft

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install MSVC toolchain
        run: rustup target add x86_64-pc-windows-msvc

      - name: Generate release notes
        id: release-notes
        uses: release-drafter/release-drafter@v6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Update Cargo.toml with new version
        shell: bash
        run: |
          version=${{ steps.release-notes.outputs.tag_name }}
          version=${version#v}
          sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$version\"/" Cargo.toml
      
      - name: Build
        run: |
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release-notes.outputs.tag_name }}
          release_name: ${{ steps.release-notes.outputs.name }}
          upload_url: ${{ steps.release-notes.outputs.upload_url }}

      - name: Upload Artifact to Release Draft
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release-notes.outputs.upload_url }}
          asset_path: target/x86_64-pc-windows-msvc/release/trees.exe
          asset_name: trees-${{ steps.release-notes.outputs.tag_name }}-x86_64-pc-windows-msvc.exe
          asset_content_type: application/octet-stream
