name: Automatic Release Draft

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install MSVC toolchain
        run: rustup target add x86_64-pc-windows-msvc

      - name: Generate release notes
        id: release-notes
        uses: release-drafter/release-drafter@v6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Update Cargo.toml with new version
        shell: bash
        run: |
          version=${{ steps.release-notes.outputs.tag_name }}
          version=${version#v}
          sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$version\"/" Cargo.toml
      
      - name: Build
        run: |
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Remove previous release asset
        id: remove-asset
        run: |
          repo_owner=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          repo_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          releases_url="https://api.github.com/repos/$repo_owner/$repo_name/releases"
          release_id=$(curl -s $releases_url | jq -r '.[0].id')
          asset_id=$(curl -s $releases_url/$release_id/assets | jq -r '.[] | select(.name == "trees-${{ steps.release-notes.outputs.tag_name }}-x86_64-pc-windows-msvc.exe").id')
          if [ -n "$asset_id" ]; then
            curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $releases_url/assets/$asset_id
          fi
      - name: Upload Artifact to Release Draft
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release-notes.outputs.upload_url }}
          asset_path: target/x86_64-pc-windows-msvc/release/trees.exe
          asset_name: trees-${{ steps.release-notes.outputs.tag_name }}-x86_64-pc-windows-msvc.exe
          asset_content_type: application/octet-stream
