name: Automatic Release Draft

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install MSVC toolchain
        run: rustup target add x86_64-pc-windows-msvc

      - name: Extract Cargo.toml version
        id: cargo_version
        run: |
          $version = Select-String -Path "Cargo.toml" -Pattern '^version\s*=\s*".*"' | ForEach-Object { $_.Matches.Groups[0].Value -replace '^version\s*=\s*"(.*)"', '$1' }
          echo "CARGO_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Generate release notes
        id: release-notes
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ env.CARGO_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Artifact to Release Draft
        run: |
          gh release upload --clobber ${{ env.VERSION }} ${{ env.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.release-notes.outputs.tag_name }}
          files: target/x86_64-pc-windows-msvc/release/trees.exe#trees-x86_64-pc-windows-msvc.exe
